# Generated by Django 6.0.3 on 2026-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Premium Gear', max_length=100)),
                ('title', models.CharField(default='Precision Archery Equipment', max_length=200)),
                ('subtitle', models.TextField(blank=True, default='Shop bows, arrows, and accessories.')),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('button_link', models.CharField(blank=True, default='/shop', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
